{% set name = "xpdsim" %}
{% set version = "0.1.5" %}
{% set sha256 = "a8137428d3b24af7d43e3b7d9dc476bdc47e6f15d58c5cb2266f9ac9ea514efc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python setup.py install --single-version-externally-managed --record record.txt
  skip: True  # [win or py2k or osx]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - ophyd
    - pyfai
    - databroker
    - bluesky

test:
  imports:
    - xpdsim
    - xpdsim.movers

about:
  home: https://github.com/xpdAcq/xpdSim
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A simulation environment for experiments at the XPD beamline at NSLS-II'

  doc_url: http://xpdacq.github.io/xpdSim/
  dev_url: https://github.com/xpdAcq/xpdSim

extra:
  recipe-maintainers:
    - CJ-Wright
