{% set name = "xpdsim" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a22454ba1b9c1f66ee9a21d42fe29ee48cfd389a3e0a28c02f12e034a07299cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky
    - databroker
    - ophyd
    - pyfai
    - suitcase-mongo

test:
  imports:
    - xpdsim
    - xpdsim.movers

about:
  home: https://github.com/xpdAcq/xpdSim
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: 'A simulation environment for experiments at the XPD beamline at NSLS-II'
  doc_url: http://xpdacq.github.io/xpdSim/
  dev_url: https://github.com/xpdAcq/xpdSim

extra:
  recipe-maintainers:
    - mrakitin
    - st3107
    - sbillinge
