{% set name = "xpdsim" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/xpdAcq/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b92e1d5be8cb97d2ae5d6f9c5fa83f406b8fc2b2bd8d3387e1fe79843fb89195

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bluesky
    - databroker <2.0.0a
    - ophyd
    - pyfai

test:
  imports:
    - xpdsim
    - xpdsim.movers

about:
  home: https://github.com/xpdAcq/xpdSim
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: 'A simulation environment for experiments at the XPD beamline at NSLS-II'
  doc_url: http://xpdacq.github.io/xpdSim/
  dev_url: https://github.com/xpdAcq/xpdSim

extra:
  recipe-maintainers:
    - st3107
    - sbillinge
