travis:
  secure:
    BINSTAR_TOKEN: uAgG6ezHbtqbrr7CvgHe1Rs/RpQIKjurnK6lIeUscjtO1G3sQeebzNvfOEqmfZMLv0gt0/iRcgmRAAjYaIL/NCl+2PAUNAgQnoRMbx/WXDQRQwBItxvBXGOUVE/JPn3J2iij4kG+LYS+apu4mehTdyo1XO1uoxpyujvajMLsgimRjqHTWR4a+Ki3Zfa1wY0/lya7G6K7OCJIQpTU27T/rEF/g1wEGTxWtRsO7mGjRTUPoXTWp7BXVDeD2BR3btAyESTr98vIKWWClPWMXrxKUeOGwOMVBwiMEPDBwv+ZYVmam4FQnmNz6AmBZQMPbhtDwzkLiUsT9YPL9Xo2913uLauy8Q0fwIdFdSZZmIW3ziTIL7lifHjnFSwzQfiLrNt6LE1uUlcu4Lw5BXnXfdwxEbC803ZHVPmZfWzFoyCpRjsTnnkbOWGe3nYNFxtBbjTZ/lGoHEEThitIJXyyKqmX6wEHsRaPg5ckNZGE+cAshBZtrpqe2i6M9r6+mvZ6FbFc6PIPxCIRzgG9sS1p1ojhR+F+kGDqSivFTyAf/2nqCK/lFK+NET1/8R7+cpTZjovUaROVVa9n0NYIr0lbnhDjBopSRMWtfNJZV1Y5lDR+GTli3pcgN5Kr7aqg7iuWxGBE845FfNNjfvmi+2btQ/YjMqOvoS+QqK13FIED5pq3ykA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
